version: '3.8'

services:
  gchat-bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    # Proper signal handling
    stop_grace_period: 30s
    # Use tini for signal handling
    init: true 